footprint: [[-0.6, -0.45], [-0.6, 0.45], [0.6, 0.45], [0.6, -0.45]]
footprint_padding: 0.1
robot_base_frame: ateks0_tf/base_link
update_frequency: 12.0
publish_frequency: 10.0
transform_tolerance: 2.0
publish_voxel_map: false
resolution: 0.05
map_type: costmap

obstacle_range: 7.0
raytrace_range: 20.0
#static:
    #map_topic: map
    #subscribe_to_updates: true
    #lethal_cost_threshold: 50

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /ateks0/laser, inf_is_valid: false}
    #laser: {topic: /lio_sam/mapping/cloud_registered, sensor_frame: velodyne, data_type: PointCloud2, clearing: true, marking: true, max_obstacle_height: -0.65, min_obstacle_height: -0.75}

inflation:
  inflation_radius: 0.6
  cost_scaling_factor: 1.5

#always_send_full_costmap: True
