global_frame: map0
rolling_window: true
track_unknown_space: false
width: 50
height: 50
static_map: false

plugins:
  #- {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,         type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
  


