controller_frequency: 5.0
controller_patience: 80.0
planner_frequency: 3.0
planner_patience: 80.0
shutdown_costmaps: true
oscillation_distance: 0.4
oscillation_timeout: 10.0
conservative_reset_dist: 0.1
cost_factor: 1.0
neutral_cost: 66
lethal_cost: 245
max_planning_retries: 5

recovery_behaviour_enabled: true
recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}] 

DWAPlannerROS:
  acc_lim_x: 0.5
  acc_lim_trans: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.0

  max_vel_x: 0.8
  min_vel_x: -0.1
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_trans: 0.8
  min_vel_trans: 0.0
  max_vel_theta: 0.5
  min_vel_theta: 0.0
  trans_stopped_vel: 0.08
  theta_stopped_vel: 0.08
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

  sim_time: 4.0
  sim_granularity: 0.03
  angular_sim_granularity: 0.05
  vx_samples: 30
  vy_samples: 0
  vtheta_samples: 60

  penalize_negative_x: false
  path_distance_bias: 50.0
  goal_distance_bias: 25.0
  occdist_scale: 0.1
  forward_point_distance: 0.6
  stop_time_buffer: 0.2
  scaling_speed: 0.2
  control_frequency: 10.0
  max_scaling_factor: 0.1

  oscillation_reset_dist: 0.1
  oscillation_reset_angle: 0.1

  prune_plan: true
  use_dwa: true

  publish_traj_pc : true
  publish_cost_grid_pc: true
